### ISSUE TITLE
Objects without properties are being ignored

### ISSUE THREAD

**Issue by acrontum-revah** [acrontum/openapi-nodegen#13]
Assuming I have the following definition:
Athlete.yml
```
type: object
  properties:
    firstName:
      type: string
    physicalDetails:
      type: object
```

The Interface generated by the Nodegen does not include the `physicalDetails` property, which is a generic object, looking like this:
Athlete.ts
```
export default interface Athlete {
  firstName?: string;
}
```

But when adding properties to the `physicalDetails` object, it does get generated.
